### ISSUE TITLE
Going up stairs triggers fly false positive on 1.13.2

### ISSUE THREAD

**Issue by MarkElf** [CraftG/WatchCat#108]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...)
Server version: paperclip 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE:  false positive - Similar to #92 - jumping/moving around a bit then going up stairs triggers setback, related to fly check.

If reporting a console error.
SERVER LOG: none

If reporting a false positive.
WATCHCAT LOG: 

If reporting a false positive/bypass. (If possible)
VIDEO: https://youtu.be/f0cAWxpmuSg

If reporting a bypass.
CLIENT: N/A

**Comment by SnackMix** [comment]
@CraftG Is there an ETA on this? We have no anti-cheat atm because the others ones I tried all have this same problem and would like to stick with WatchCat as our anti-cheat.
