### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Clasher31HD** [CraftG/WatchCat#12]
https://pastebin.com/8WJwiQMb
https://pastebin.com/GnwpF027
https://pastebin.com/J4BeqW1C

The first Error occured when i use Kick (PacketSpam) with LiquidBounce

**Comment by CraftG** [comment]
I will fix them.

**Comment by TrademarkTM** [comment]
I'm having this error:
https://hastebin.com/alewolegun.pl
