### ISSUE TITLE
plugin not work Spigot 1.13.2 build 2004

### ISSUE THREAD

**Issue by Dancbeunny98** [CraftG/WatchCat#125]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...)
Server version:  Spigot 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: plugin not see server

If reporting a console error.
SERVER LOG:  no logs

If reporting a false positive.
WATCHCAT LOG:  no llogs

If reporting a false positive/bypass. (If possible)
PHOTO:
![image](https://user-images.githubusercontent.com/37336183/50411635-a019f500-0812-11e9-94de-fa955c578624.png)
  

If reporting a bypass.
CLIENT: N0

**Comment by MarkElf** [comment]
You're missing protocol lib.
