### ISSUE TITLE
Bypass: Aristois Client bypasses everything except for KillAura

### ISSUE THREAD

**Issue by Sammy5k** [CraftG/WatchCat#130]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: Spigot
Server version: 1.13.2

ISSUE TYPE: Bypass

If reporting a bypass.
CLIENT: I used Aristois to test it. I found that the hacked client can friend the checks (the entity that checks for hacks) in order to bypass certain checks such as autoclicker, and sometime killaura. The player is able to freely change their speed, have nofall, glide, use inventory hacks. I also get detected for Killaura (when im not even using killaura), when I get hit by the client using KillAura.

**Comment by CraftG** [comment]
Probably fixed
