### ISSUE TITLE
WatchCat cannot be loaded

### ISSUE THREAD

**Issue by NaNaShiSan1** [CraftG/WatchCat#38]
Config are deleted.

Server version : CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Plugins: WatchCat 1.6.8.6, ProtocolLib 4.2.0, ViaVersion 1.3.0
Logs: [https://hastebin.com/xijahahifi.md](https://hastebin.com/xijahahifi.md)

**Comment by CraftG** [comment]
Now fix
