### ISSUE TITLE
IrregularMovement False positive

### ISSUE THREAD

**Issue by NaNaShiSan1** [CraftG/WatchCat#43]
False positives will occur when If you step to a special hitbox block.
Affected blocks (and cart) : Snow(snow layer), fence, fence+carpet, hopper, bed, trapdoor, and minecart. (maybe even more)

Video: [https://youtu.be/vh2YLK5TkQw](https://youtu.be/vh2YLK5TkQw)
*Config is modified for testing, but false positive is working on default config.

**Comment by CraftG** [comment]
I found it, and I am fixing now :)

**Comment by NaNaShiSan1** [comment]
😜
