### ISSUE TITLE
Suggestion(or maybe a bug report?): Disable Anti-Freecam when teleporting

### ISSUE THREAD

**Issue by NaNaShiSan1** [CraftG/WatchCat#44]
It's often happening in practice server, but when if you teleport to another world or another player, teleportation will be canceled by sometimes.
Can you do something about that?
Thanks.

**Comment by CraftG** [comment]
hmmm... I have not encountered this problem because Freecam-teleport only turned on when the player is standing still.
If this problem occurs frequently, you can turn it off in BadPackets in check.yml. I will make some changes in the next version.

**Comment by CraftG** [comment]
Is the player pulled back after the teleportation or the teleportation plugin cancels the teleportation?

**Comment by NaNaShiSan1** [comment]
Player pulled back after the teleportation.

**Comment by CraftG** [comment]
okey, i know
