### ISSUE TITLE
player did not get kick when hit entity

### ISSUE THREAD

**Issue by hacalios** [CraftG/WatchCat#46]
my config killaura entity https://hastebin.com/soyosibole.bash
player hit entity fly around them and nothing happened

**Comment by CraftG** [comment]
Try to set the KillauraEntity.action to
    10:
    - 'wc kick %player% Suspicious attack. Killaura?'
    - 'wc notification Player %player% is kicked out by using Killaura'
    11:
    - 'wc kick %player% Suspicious attack. Killaura?'
    - 'wc notification Player %player% is kicked out by using Killaura'
    12:
    - 'wc kick %player% Suspicious attack. Killaura?'
    - 'wc notification Player %player% is kicked out by using Killaura'

**Comment by hacalios** [comment]
now it's work lol
