### ISSUE TITLE
消息bug和走路BUG还有封禁BUG

### ISSUE THREAD

**Issue by g530775** [CraftG/WatchCat#54]
玩家跑跳久了就会被T出游戏
还有如果一名玩家使用飞行一类的话到了被ban的时候会刷出很多只很多只守护者虽然刷了很多最后被封禁如果那位玩家到处跑可能会使守护者被摔死刷出许多的生鱼和那什么
[https://s1.ax1x.com/2018/08/12/PcgtO0.png](url)

**Comment by CraftG** [comment]
你使用的是最新版1.7.0.4吗？

**Comment by g530775** [comment]
没错...1.7.0.4你可以亲自试试...如果跑跳不正确的话至少封禁的那些守护者就是刷很多然后玩家移动如果有方块直接摔死然后掉落东西

**Comment by CraftG** [comment]
ok

**Comment by g530775** [comment]
对了...我是测试的fly封禁...我把第二条wc kick改了变成 say...然后刷屏，第60次的直接wc ban然后没关掉fly依旧刷很多很多守护者...我电脑都卡了至少不下200只

**Comment by CraftG** [comment]
上次你的log
plugins/WatchCat/logs

**Comment by CraftG** [comment]
不需要改配置文件

**Comment by g530775** [comment]
[2018-8-12.log](https://github.com/CraftG/WatchCat/files/2280989/2018-8-12.log)
如果不改一下第二条那么就只会踢出踢出永远不会被封禁...不知道是不是个BUG

**Comment by CraftG** [comment]
我测试了好像没有fly的误报。其他的我会修复。
如果有时间来测试服试试 test.mrcraftgoo.xyz

**Comment by g530775** [comment]
那么我去试试...我的是改掉了第二个kick...因为不知道为什么永远都不会ban只会被踢出服务器
