### ISSUE TITLE
Suggestion: Create an issue report template(about issue tracker, not watchcat!)

### ISSUE THREAD

**Issue by NaNaShiSan1** [CraftG/WatchCat#75]
Create an issue report template is useful when reporting false positive or bypass, and console error.
(Example, typing server version, watchcat version, logs, and etc)

Example, AAC issue tracker.([https://github.com/konsolas/AAC-Issues/blob/master/ISSUE_TEMPLATE.md](https://github.com/konsolas/AAC-Issues/blob/master/ISSUE_TEMPLATE.md))

**Comment by CraftG** [comment]
I  will do it
