### ISSUE TITLE
Fly is bypassable with ~0.36Blocks/Tick speed

### ISSUE THREAD

**Issue by NaNaShiSan1** [CraftG/WatchCat#79]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...)
Server version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT

bypass/false positive/bug/error/suggestion
ISSUE TYPE: bypass

If reporting a console error.
SERVER LOG: 

If reporting a false positive.
WATCHCAT LOG: 

If reporting a false positive/bypass. (If possible)
VIDEO: [https://streamable.com/l1ptv](https://streamable.com/l1ptv) (It's viewable in China! :D)

If reporting a bypass.
CLIENT: LiquidBounce

**Comment by CraftG** [comment]
fly check is still in development. I will improve it
