### ISSUE TITLE
Jump out and on the Water

### ISSUE THREAD

**Issue by Sprungente** [CraftG/WatchCat#98]
Player can't sometimes jump out the water.

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...)
Server version: 1.13.1

bypass/_**false positive**_/**bug**/error/suggestion

If reporting a false positive.
WATCHCAT LOG: 
https://hastebin.com/agariloqin.cs

If reporting a bypass.
CLIENT: No Clients used

**Comment by CraftG** [comment]
Thanks, it will be fixed :)

**Comment by Sprungente** [comment]
https://youtu.be/JibwyfPsKK8
