### ISSUE TITLE
Going into a boat

### ISSUE THREAD

**Issue by Sprungente** [CraftG/WatchCat#99]
Player can't go into a boat

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...)
Server version: Spigot 1.13.1

bypass/**false positive**/bug/error/suggestion

If reporting a console error.
SERVER LOG: Nonne

If reporting a false positive.
WATCHCAT LOG: https://hastebin.com/ulemorurer.cs

**Comment by CraftG** [comment]
Fixed.
